/**
* Do not edit directly
* Generated on Sun, 13 Nov 2022 20:06:31 GMT
*/
module.exports = {
  border: {
    border1: 1,
    border2: 2,
    border3: 3,
    border4: 4,
    none: 0
  },
  color: {
    amber: '#faca69',
    amberDark: '#b4872c',
    amberLight: '#fff9ee',
    bgModal: 'rgba(244, 244, 247, 0.97)',
    black: '#000000',
    dark10: 'rgba(0, 0, 0, 0.1)',
    dark20: 'rgba(0, 0, 0, 0.2)',
    dark40: 'rgba(0, 0, 0, 0.4)',
    dark60: 'rgba(0, 0, 0, 0.6)',
    dark80: 'rgba(0, 0, 0, 0.8)',
    dark97: 'rgba(0, 0, 0, 0.97)',
    greenAccessible: '#2b8000',
    greenDarkFern: '#163e06',
    greenPanache: '#f4f9f2',
    greenSanFelix: '#1f5c09',
    greenTelus: '#66cc00',
    greenTusk: '#e3f6d1',
    greenYellow: '#bfe797',
    greyAlabaster: '#fafafa',
    greyAthens: '#f4f4f7',
    greyCharcoal: '#414547',
    greyCloud: '#b2b9bf',
    greyMystic: '#e3e6e8',
    greyShuttle: '#676e73',
    greyThunder: '#2c2e30',
    light10: 'rgba(255, 255, 255, 0.1)',
    light20: 'rgba(255, 255, 255, 0.2)',
    light40: 'rgba(255, 255, 255, 0.4)',
    light60: 'rgba(255, 255, 255, 0.6)',
    light80: 'rgba(255, 255, 255, 0.8)',
    light97: 'rgba(255, 255, 255, 0.97)',
    purpleDark: '#3f2a54',
    purpleDeluge: '#7c53a5',
    purpleEminence: '#613889',
    purpleTelus: '#4b286d',
    red: '#e12339',
    redDark: '#c12335',
    redDarker: '#560c0c',
    redLight: '#fff6f8',
    transparent: 'rgba(0, 0, 0, 0)',
    white: '#ffffff'
  },
  duration: {
    duration250: 250,
    duration300: 300
  },
  font: {
    HelveticaNow: {
      300: '@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-300.otf',
      400: '@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-400.woff',
      500: '@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-500.woff',
      700: '@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-700.woff'
    },
    HelveticaNowOTF: {
      400: '@telus-uds/palette-allium/build/rn/fonts/HelveticaNowOTF-400.otf',
      500: '@telus-uds/palette-allium/build/rn/fonts/HelveticaNowOTF-500.otf',
      700: '@telus-uds/palette-allium/build/rn/fonts/HelveticaNowOTF-700.otf'
    }
  },
  fontSize: {
    size12: 12,
    size14: 14,
    size16: 16,
    size20: 20,
    size24: 24,
    size28: 28,
    size36: 36,
    size40: 40,
    size56: 56,
    size64: 64
  },
  gradient: {
    base: {
      type: 'radial',
      stops: [
        {
          stop: 0,
          color: '#ffffff'
        },
        {
          stop: 1,
          color: '#f4f4f7'
        }
      ],
      specification: '44.58% 44.58% at 81.13% 36.79%'
    },
    brand: {
      type: 'linear',
      stops: [
        {
          stop: 0,
          color: '#4b286d'
        },
        {
          stop: 1,
          color: '#613889'
        }
      ],
      angle: 135
    },
    green: {
      type: 'linear',
      stops: [
        {
          stop: 0,
          color: '#00784a'
        },
        {
          stop: 1,
          color: '#66cc00'
        }
      ],
      angle: 135
    },
    neutral: {
      type: 'linear',
      stops: [
        {
          stop: 0,
          color: '#ffffff'
        },
        {
          stop: 1,
          color: '#f4f4f7'
        }
      ],
      angle: 180
    },
    purple: {
      type: 'linear',
      stops: [
        {
          stop: 0,
          color: '#4b286d'
        },
        {
          stop: 1,
          color: '#e53293'
        }
      ],
      angle: 135
    }
  },
  icon: {
    Accessible: '@telus-uds/palette-allium/build/rn/icons/accessible.icon.svg',
    Add: '@telus-uds/palette-allium/build/rn/icons/add.icon.svg',
    AddUser: '@telus-uds/palette-allium/build/rn/icons/add-user.icon.svg',
    AlarmClock: '@telus-uds/palette-allium/build/rn/icons/alarm-clock.icon.svg',
    Ambulance: '@telus-uds/palette-allium/build/rn/icons/ambulance.icon.svg',
    ArrowDown: '@telus-uds/palette-allium/build/rn/icons/arrow-down.icon.svg',
    ArrowLeft: '@telus-uds/palette-allium/build/rn/icons/arrow-left.icon.svg',
    ArrowRight: '@telus-uds/palette-allium/build/rn/icons/arrow-right.icon.svg',
    ArrowUp: '@telus-uds/palette-allium/build/rn/icons/arrow-up.icon.svg',
    ArtificialIntelligence: '@telus-uds/palette-allium/build/rn/icons/artificial-intelligence.icon.svg',
    Attention: '@telus-uds/palette-allium/build/rn/icons/attention.icon.svg',
    Award: '@telus-uds/palette-allium/build/rn/icons/award.icon.svg',
    Baby: '@telus-uds/palette-allium/build/rn/icons/baby.icon.svg',
    BabyBoy: '@telus-uds/palette-allium/build/rn/icons/baby-boy.icon.svg',
    BabyGirl: '@telus-uds/palette-allium/build/rn/icons/baby-girl.icon.svg',
    BackToSchool: '@telus-uds/palette-allium/build/rn/icons/back-to-school.icon.svg',
    Bank: '@telus-uds/palette-allium/build/rn/icons/bank.icon.svg',
    BatteryCar: '@telus-uds/palette-allium/build/rn/icons/battery-car.icon.svg',
    BatteryCharging: '@telus-uds/palette-allium/build/rn/icons/battery-charging.icon.svg',
    Bell: '@telus-uds/palette-allium/build/rn/icons/bell.icon.svg',
    Bill: '@telus-uds/palette-allium/build/rn/icons/bill.icon.svg',
    Bookmark: '@telus-uds/palette-allium/build/rn/icons/bookmark.icon.svg',
    Briefcase: '@telus-uds/palette-allium/build/rn/icons/briefcase.icon.svg',
    BulletFill: '@telus-uds/palette-allium/build/rn/icons/bullet-fill.icon.svg',
    Calendar: '@telus-uds/palette-allium/build/rn/icons/calendar.icon.svg',
    Call: '@telus-uds/palette-allium/build/rn/icons/call.icon.svg',
    CallForward: '@telus-uds/palette-allium/build/rn/icons/call-forward.icon.svg',
    CallOut: '@telus-uds/palette-allium/build/rn/icons/call-out.icon.svg',
    CallReceive: '@telus-uds/palette-allium/build/rn/icons/call-receive.icon.svg',
    CallTalking: '@telus-uds/palette-allium/build/rn/icons/call-talking.icon.svg',
    Camera: '@telus-uds/palette-allium/build/rn/icons/camera.icon.svg',
    CanUs: '@telus-uds/palette-allium/build/rn/icons/can-us.icon.svg',
    Car: '@telus-uds/palette-allium/build/rn/icons/car.icon.svg',
    CaretDown: '@telus-uds/palette-allium/build/rn/icons/caret-down.icon.svg',
    CaretUp: '@telus-uds/palette-allium/build/rn/icons/caret-up.icon.svg',
    CartEmptyBold: '@telus-uds/palette-allium/build/rn/icons/cart-empty-bold.icon.svg',
    CartFilledBold: '@telus-uds/palette-allium/build/rn/icons/cart-filled-bold.icon.svg',
    Channels: '@telus-uds/palette-allium/build/rn/icons/channels.icon.svg',
    ChartsBar1: '@telus-uds/palette-allium/build/rn/icons/charts-bar1.icon.svg',
    ChartsBar2: '@telus-uds/palette-allium/build/rn/icons/charts-bar2.icon.svg',
    ChartsLine: '@telus-uds/palette-allium/build/rn/icons/charts-line.icon.svg',
    Chat1: '@telus-uds/palette-allium/build/rn/icons/chat1.icon.svg',
    Chat2: '@telus-uds/palette-allium/build/rn/icons/chat2.icon.svg',
    ChatSupport: '@telus-uds/palette-allium/build/rn/icons/chat-support.icon.svg',
    Check: '@telus-uds/palette-allium/build/rn/icons/check.icon.svg',
    Checkmark: '@telus-uds/palette-allium/build/rn/icons/checkmark.icon.svg',
    ChevronLeft: '@telus-uds/palette-allium/build/rn/icons/chevron-left.icon.svg',
    ChevronRight: '@telus-uds/palette-allium/build/rn/icons/chevron-right.icon.svg',
    Clipboard: '@telus-uds/palette-allium/build/rn/icons/clipboard.icon.svg',
    Close: '@telus-uds/palette-allium/build/rn/icons/close.icon.svg',
    ClosedCaptions: '@telus-uds/palette-allium/build/rn/icons/closed-captions.icon.svg',
    CloudDownload: '@telus-uds/palette-allium/build/rn/icons/cloud-download.icon.svg',
    CloudSync: '@telus-uds/palette-allium/build/rn/icons/cloud-sync.icon.svg',
    CloudUpload: '@telus-uds/palette-allium/build/rn/icons/cloud-upload.icon.svg',
    Collaboration: '@telus-uds/palette-allium/build/rn/icons/collaboration.icon.svg',
    Compass: '@telus-uds/palette-allium/build/rn/icons/compass.icon.svg',
    ComputerNetwork: '@telus-uds/palette-allium/build/rn/icons/computer-network.icon.svg',
    Contract: '@telus-uds/palette-allium/build/rn/icons/contract.icon.svg',
    CreditCard: '@telus-uds/palette-allium/build/rn/icons/credit-card.icon.svg',
    Cronometer: '@telus-uds/palette-allium/build/rn/icons/cronometer.icon.svg',
    CssActivations: '@telus-uds/palette-allium/build/rn/icons/css-activations.icon.svg',
    DataLimit: '@telus-uds/palette-allium/build/rn/icons/data-limit.icon.svg',
    Deals: '@telus-uds/palette-allium/build/rn/icons/deals.icon.svg',
    Delete: '@telus-uds/palette-allium/build/rn/icons/delete.icon.svg',
    Delivery: '@telus-uds/palette-allium/build/rn/icons/delivery.icon.svg',
    Devices: '@telus-uds/palette-allium/build/rn/icons/devices.icon.svg',
    Diagram: '@telus-uds/palette-allium/build/rn/icons/diagram.icon.svg',
    Diamond: '@telus-uds/palette-allium/build/rn/icons/diamond.icon.svg',
    Direction: '@telus-uds/palette-allium/build/rn/icons/direction.icon.svg',
    Document: '@telus-uds/palette-allium/build/rn/icons/document.icon.svg',
    Donate: '@telus-uds/palette-allium/build/rn/icons/donate.icon.svg',
    Download: '@telus-uds/palette-allium/build/rn/icons/download.icon.svg',
    DownloadPdf: '@telus-uds/palette-allium/build/rn/icons/download-pdf.icon.svg',
    DownloadPdfs: '@telus-uds/palette-allium/build/rn/icons/download-pdfs.icon.svg',
    Edit: '@telus-uds/palette-allium/build/rn/icons/edit.icon.svg',
    Email: '@telus-uds/palette-allium/build/rn/icons/email.icon.svg',
    Escalations: '@telus-uds/palette-allium/build/rn/icons/escalations.icon.svg',
    FavouriteNetwork: '@telus-uds/palette-allium/build/rn/icons/favourite-network.icon.svg',
    Files: '@telus-uds/palette-allium/build/rn/icons/files.icon.svg',
    Fingerprint: '@telus-uds/palette-allium/build/rn/icons/fingerprint.icon.svg',
    Firewall: '@telus-uds/palette-allium/build/rn/icons/firewall.icon.svg',
    Flag: '@telus-uds/palette-allium/build/rn/icons/flag.icon.svg',
    FullscreenExpand: '@telus-uds/palette-allium/build/rn/icons/fullscreen-expand.icon.svg',
    FullscreenMinimize: '@telus-uds/palette-allium/build/rn/icons/fullscreen-minimize.icon.svg',
    Gift: '@telus-uds/palette-allium/build/rn/icons/gift.icon.svg',
    Globe1: '@telus-uds/palette-allium/build/rn/icons/globe1.icon.svg',
    Globe2: '@telus-uds/palette-allium/build/rn/icons/globe2.icon.svg',
    Grid: '@telus-uds/palette-allium/build/rn/icons/grid.icon.svg',
    HeadBoth: '@telus-uds/palette-allium/build/rn/icons/head-both.icon.svg',
    HeadFemale: '@telus-uds/palette-allium/build/rn/icons/head-female.icon.svg',
    HeadMale: '@telus-uds/palette-allium/build/rn/icons/head-male.icon.svg',
    Headset: '@telus-uds/palette-allium/build/rn/icons/headset.icon.svg',
    Heart: '@telus-uds/palette-allium/build/rn/icons/heart.icon.svg',
    Heartbeat: '@telus-uds/palette-allium/build/rn/icons/heartbeat.icon.svg',
    Helpdesk: '@telus-uds/palette-allium/build/rn/icons/helpdesk.icon.svg',
    Home: '@telus-uds/palette-allium/build/rn/icons/home.icon.svg',
    HomeSecurity: '@telus-uds/palette-allium/build/rn/icons/home-security.icon.svg',
    IDTag: '@telus-uds/palette-allium/build/rn/icons/idtag.icon.svg',
    Infinite: '@telus-uds/palette-allium/build/rn/icons/infinite.icon.svg',
    Information: '@telus-uds/palette-allium/build/rn/icons/information.icon.svg',
    Internet: '@telus-uds/palette-allium/build/rn/icons/internet.icon.svg',
    Invisible: '@telus-uds/palette-allium/build/rn/icons/invisible.icon.svg',
    Key: '@telus-uds/palette-allium/build/rn/icons/key.icon.svg',
    Laptop: '@telus-uds/palette-allium/build/rn/icons/laptop.icon.svg',
    Layers: '@telus-uds/palette-allium/build/rn/icons/layers.icon.svg',
    Lifesaver: '@telus-uds/palette-allium/build/rn/icons/lifesaver.icon.svg',
    Lightbulb: '@telus-uds/palette-allium/build/rn/icons/lightbulb.icon.svg',
    LinkExternal: '@telus-uds/palette-allium/build/rn/icons/link-external.icon.svg',
    List: '@telus-uds/palette-allium/build/rn/icons/list.icon.svg',
    LocationAdd: '@telus-uds/palette-allium/build/rn/icons/location-add.icon.svg',
    LocationHome: '@telus-uds/palette-allium/build/rn/icons/location-home.icon.svg',
    LocationIneligible: '@telus-uds/palette-allium/build/rn/icons/location-ineligible.icon.svg',
    LocationMap: '@telus-uds/palette-allium/build/rn/icons/location-map.icon.svg',
    LocationRegular: '@telus-uds/palette-allium/build/rn/icons/location-regular.icon.svg',
    LocationRemove: '@telus-uds/palette-allium/build/rn/icons/location-remove.icon.svg',
    LocationSuccess: '@telus-uds/palette-allium/build/rn/icons/location-success.icon.svg',
    LocationVerified: '@telus-uds/palette-allium/build/rn/icons/location-verified.icon.svg',
    LockClosed: '@telus-uds/palette-allium/build/rn/icons/lock-closed.icon.svg',
    LockOpened: '@telus-uds/palette-allium/build/rn/icons/lock-opened.icon.svg',
    LoginForm: '@telus-uds/palette-allium/build/rn/icons/login-form.icon.svg',
    Magnify: '@telus-uds/palette-allium/build/rn/icons/magnify.icon.svg',
    Map: '@telus-uds/palette-allium/build/rn/icons/map.icon.svg',
    Medical: '@telus-uds/palette-allium/build/rn/icons/medical.icon.svg',
    Messaging: '@telus-uds/palette-allium/build/rn/icons/messaging.icon.svg',
    Mobility: '@telus-uds/palette-allium/build/rn/icons/mobility.icon.svg',
    Modal: '@telus-uds/palette-allium/build/rn/icons/modal.icon.svg',
    Money: '@telus-uds/palette-allium/build/rn/icons/money.icon.svg',
    Movie: '@telus-uds/palette-allium/build/rn/icons/movie.icon.svg',
    Music: '@telus-uds/palette-allium/build/rn/icons/music.icon.svg',
    Muted: '@telus-uds/palette-allium/build/rn/icons/muted.icon.svg',
    Networking: '@telus-uds/palette-allium/build/rn/icons/networking.icon.svg',
    News: '@telus-uds/palette-allium/build/rn/icons/news.icon.svg',
    NextGenFirewall: '@telus-uds/palette-allium/build/rn/icons/next-gen-firewall.icon.svg',
    NoContract: '@telus-uds/palette-allium/build/rn/icons/no-contract.icon.svg',
    NotifyBold: '@telus-uds/palette-allium/build/rn/icons/notify-bold.icon.svg',
    Office: '@telus-uds/palette-allium/build/rn/icons/office.icon.svg',
    Offices: '@telus-uds/palette-allium/build/rn/icons/offices.icon.svg',
    OnDemand: '@telus-uds/palette-allium/build/rn/icons/on-demand.icon.svg',
    OnTheGo: '@telus-uds/palette-allium/build/rn/icons/on-the-go.icon.svg',
    OnlineSecurity: '@telus-uds/palette-allium/build/rn/icons/online-security.icon.svg',
    Paperless: '@telus-uds/palette-allium/build/rn/icons/paperless.icon.svg',
    Passport: '@telus-uds/palette-allium/build/rn/icons/passport.icon.svg',
    Pause: '@telus-uds/palette-allium/build/rn/icons/pause.icon.svg',
    Phone: '@telus-uds/palette-allium/build/rn/icons/phone.icon.svg',
    PhoneBusiness: '@telus-uds/palette-allium/build/rn/icons/phone-business.icon.svg',
    PhoneHome: '@telus-uds/palette-allium/build/rn/icons/phone-home.icon.svg',
    PhoneReception: '@telus-uds/palette-allium/build/rn/icons/phone-reception.icon.svg',
    Photo: '@telus-uds/palette-allium/build/rn/icons/photo.icon.svg',
    Photos: '@telus-uds/palette-allium/build/rn/icons/photos.icon.svg',
    PiggyBank: '@telus-uds/palette-allium/build/rn/icons/piggy-bank.icon.svg',
    PikTV: '@telus-uds/palette-allium/build/rn/icons/pik-tv.icon.svg',
    Play: '@telus-uds/palette-allium/build/rn/icons/play.icon.svg',
    PlaySolid: '@telus-uds/palette-allium/build/rn/icons/play-solid.icon.svg',
    PlayVideo: '@telus-uds/palette-allium/build/rn/icons/play-video.icon.svg',
    Preference: '@telus-uds/palette-allium/build/rn/icons/preference.icon.svg',
    Print: '@telus-uds/palette-allium/build/rn/icons/print.icon.svg',
    PrivateCloud: '@telus-uds/palette-allium/build/rn/icons/private-cloud.icon.svg',
    Profile: '@telus-uds/palette-allium/build/rn/icons/profile.icon.svg',
    ProfileBold: '@telus-uds/palette-allium/build/rn/icons/profile-bold.icon.svg',
    Question: '@telus-uds/palette-allium/build/rn/icons/question.icon.svg',
    QuoteLeft: '@telus-uds/palette-allium/build/rn/icons/quote-left.icon.svg',
    Radar: '@telus-uds/palette-allium/build/rn/icons/radar.icon.svg',
    Receipt: '@telus-uds/palette-allium/build/rn/icons/receipt.icon.svg',
    Record: '@telus-uds/palette-allium/build/rn/icons/record.icon.svg',
    Refresh: '@telus-uds/palette-allium/build/rn/icons/refresh.icon.svg',
    RemoteControl: '@telus-uds/palette-allium/build/rn/icons/remote-control.icon.svg',
    Replay: '@telus-uds/palette-allium/build/rn/icons/replay.icon.svg',
    Router: '@telus-uds/palette-allium/build/rn/icons/router.icon.svg',
    Search: '@telus-uds/palette-allium/build/rn/icons/search.icon.svg',
    SearchBold: '@telus-uds/palette-allium/build/rn/icons/search-bold.icon.svg',
    SecurityCamera: '@telus-uds/palette-allium/build/rn/icons/security-camera.icon.svg',
    SecurityHouse: '@telus-uds/palette-allium/build/rn/icons/security-house.icon.svg',
    SecurityMobile: '@telus-uds/palette-allium/build/rn/icons/security-mobile.icon.svg',
    SecuritySettings: '@telus-uds/palette-allium/build/rn/icons/security-settings.icon.svg',
    Server: '@telus-uds/palette-allium/build/rn/icons/server.icon.svg',
    ServiceTruck: '@telus-uds/palette-allium/build/rn/icons/service-truck.icon.svg',
    Settings: '@telus-uds/palette-allium/build/rn/icons/settings.icon.svg',
    SettingsBold: '@telus-uds/palette-allium/build/rn/icons/settings-bold.icon.svg',
    SettingsSolid: '@telus-uds/palette-allium/build/rn/icons/settings-solid.icon.svg',
    SharedAccount: '@telus-uds/palette-allium/build/rn/icons/shared-account.icon.svg',
    Shop: '@telus-uds/palette-allium/build/rn/icons/shop.icon.svg',
    SignPost: '@telus-uds/palette-allium/build/rn/icons/sign-post.icon.svg',
    Signal: '@telus-uds/palette-allium/build/rn/icons/signal.icon.svg',
    SimCard: '@telus-uds/palette-allium/build/rn/icons/sim-card.icon.svg',
    SmartWearSecurity: '@telus-uds/palette-allium/build/rn/icons/smart-wear-security.icon.svg',
    Soccer: '@telus-uds/palette-allium/build/rn/icons/soccer.icon.svg',
    Speaker: '@telus-uds/palette-allium/build/rn/icons/speaker.icon.svg',
    SpeakerPhone: '@telus-uds/palette-allium/build/rn/icons/speaker-phone.icon.svg',
    Speed: '@telus-uds/palette-allium/build/rn/icons/speed.icon.svg',
    SpeedReduced: '@telus-uds/palette-allium/build/rn/icons/speed-reduced.icon.svg',
    StatusError: '@telus-uds/palette-allium/build/rn/icons/status-error.icon.svg',
    StatusSuccess: '@telus-uds/palette-allium/build/rn/icons/status-success.icon.svg',
    StatusWarning: '@telus-uds/palette-allium/build/rn/icons/status-warning.icon.svg',
    Subtract: '@telus-uds/palette-allium/build/rn/icons/subtract.icon.svg',
    Success: '@telus-uds/palette-allium/build/rn/icons/success.icon.svg',
    Suitcase: '@telus-uds/palette-allium/build/rn/icons/suitcase.icon.svg',
    Support: '@telus-uds/palette-allium/build/rn/icons/support.icon.svg',
    TV: '@telus-uds/palette-allium/build/rn/icons/tv.icon.svg',
    TVChoiceAndFlexibility: '@telus-uds/palette-allium/build/rn/icons/tvchoice-and-flexibility.icon.svg',
    Tablet: '@telus-uds/palette-allium/build/rn/icons/tablet.icon.svg',
    Target: '@telus-uds/palette-allium/build/rn/icons/target.icon.svg',
    Tasks: '@telus-uds/palette-allium/build/rn/icons/tasks.icon.svg',
    ThumbsUp: '@telus-uds/palette-allium/build/rn/icons/thumbs-up.icon.svg',
    Time: '@telus-uds/palette-allium/build/rn/icons/time.icon.svg',
    Times: '@telus-uds/palette-allium/build/rn/icons/times.icon.svg',
    TowTruck: '@telus-uds/palette-allium/build/rn/icons/tow-truck.icon.svg',
    Transmitter: '@telus-uds/palette-allium/build/rn/icons/transmitter.icon.svg',
    Unmuted: '@telus-uds/palette-allium/build/rn/icons/unmuted.icon.svg',
    Upload: '@telus-uds/palette-allium/build/rn/icons/upload.icon.svg',
    UploadToCloud: '@telus-uds/palette-allium/build/rn/icons/upload-to-cloud.icon.svg',
    UsbCable: '@telus-uds/palette-allium/build/rn/icons/usb-cable.icon.svg',
    User: '@telus-uds/palette-allium/build/rn/icons/user.icon.svg',
    UserAddBold: '@telus-uds/palette-allium/build/rn/icons/user-add-bold.icon.svg',
    Users: '@telus-uds/palette-allium/build/rn/icons/users.icon.svg',
    VideoChat: '@telus-uds/palette-allium/build/rn/icons/video-chat.icon.svg',
    VideoGames: '@telus-uds/palette-allium/build/rn/icons/video-games.icon.svg',
    Visible: '@telus-uds/palette-allium/build/rn/icons/visible.icon.svg',
    Warranty: '@telus-uds/palette-allium/build/rn/icons/warranty.icon.svg',
    Watch: '@telus-uds/palette-allium/build/rn/icons/watch.icon.svg',
    WifiBoost: '@telus-uds/palette-allium/build/rn/icons/wifi-boost.icon.svg',
    WifiCloud: '@telus-uds/palette-allium/build/rn/icons/wifi-cloud.icon.svg'
  },
  letterSpacing: {
    condensed: -0.039,
    loose: -0.017,
    medium: -0.035
  },
  lineHeight: {
    ratio10to7: 1.42857142857,
    ratio11to9: 1.22222222222,
    ratio1to1: 1,
    ratio3to2: 1.5,
    ratio4to3: 1.33333333333,
    ratio5to4: 1.25,
    ratio6to5: 1.2,
    ratio7to5: 1.4,
    ratio8to5: 1.6,
    ratio8to7: 1.14285714286,
    ratio9to7: 1.28571428571,
    ratio9to8: 1.125
  },
  opacity: {},
  radius: {
    none: 0,
    pill32: 32,
    radius1: 1,
    radius12: 12,
    radius4: 4,
    radius6: 6,
    radius8: 8
  },
  shadow: {
    elevation1: {
      inset: false,
      offsetX: 0,
      offsetY: 4,
      blur: 8,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.1)'
    },
    elevation2: {
      inset: false,
      offsetX: 0,
      offsetY: 12,
      blur: 12,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.03)'
    },
    elevation3: {
      inset: false,
      offsetX: 0,
      offsetY: 32,
      blur: 32,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.03)'
    },
    surfaceEmboss: {
      inset: true,
      offsetX: 0,
      offsetY: 2,
      blur: 2,
      spread: 0,
      color: 'rgba(255, 255, 255, 0.8)'
    },
    surfaceInset: {
      inset: true,
      offsetX: 0,
      offsetY: 2,
      blur: 2,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.1)'
    },
    surfaceRaised: {
      inset: false,
      offsetX: 0,
      offsetY: 2,
      blur: 2,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.1)'
    }
  },
  size: {
    size0: 0,
    size1: 1,
    size10: 10,
    size12: 12,
    size120: 120,
    size144: 144,
    size16: 16,
    size192: 192,
    size2: 2,
    size20: 20,
    size24: 24,
    size264: 264,
    size28: 28,
    size288: 288,
    size3: 3,
    size32: 32,
    size320: 320,
    size36: 36,
    size4: 4,
    size40: 40,
    size44: 44,
    size48: 48,
    size480: 480,
    size56: 56,
    size576: 576,
    size630: 630,
    size64: 64,
    size72: 72,
    size768: 768,
    size8: 8,
    size80: 80,
    size96: 96
  }
}
