module.exports.HelveticaNow300normal= require('@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-300.otf')
module.exports.HelveticaNow400normal= require('@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-400.woff')
module.exports.HelveticaNow500normal= require('@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-500.woff')
module.exports.HelveticaNow700normal= require('@telus-uds/palette-allium/build/rn/fonts/HelveticaNow-700.woff')
module.exports.HelveticaNowOTF400normal= require('@telus-uds/palette-allium/build/rn/fonts/HelveticaNowOTF-400.otf')
module.exports.HelveticaNowOTF500normal= require('@telus-uds/palette-allium/build/rn/fonts/HelveticaNowOTF-500.otf')
module.exports.HelveticaNowOTF700normal= require('@telus-uds/palette-allium/build/rn/fonts/HelveticaNowOTF-700.otf')
