name: Update Pod repo

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Update Cocoapod
      run: |
        npm install -g podspec-bump
        for file in /Users/runner/work/iOS-allium-palette/iOS-allium-palette; do
            echo "${file##*/}"
        done
        # podspec-bump -p /Users/runner/work/iOS-allium-palette/iOS-Allium-palette.podspec
        # git commit -am "bump `podspec-bump --dump-version`" 
        # git tag "`podspec-bump --dump-version`"
        # git push --tags
        # pod trunk push --allow-warnings
      shell: sh