name: Update Pod repo

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Update Cocoapod
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Test and Lint
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'
        